import { Platform, StyleSheet } from 'react-native';
import { colors, fonts, radii, shadows, spacing, typography } from '@/shared/design-system';

export const styles = StyleSheet.create({
    screen: { backgroundColor: colors.canvas, flex: 1 },
    appShell: { backgroundColor: colors.canvas, flex: 1, minHeight: 0 },
    appShellDesktop: { paddingHorizontal: 0 },
    flexScroll: { flex: 1, minHeight: 0 },
    pageTransition: { flex: 1, minHeight: 0 },
    webFreeScroll: { flex: 1, minHeight: 0, overflowX: 'hidden', overflowY: 'auto' } as object,
    bootScreen: { alignItems: 'center', backgroundColor: colors.canvas, flex: 1, justifyContent: 'center', padding: spacing[6] },
    bootCard: { alignItems: 'center', borderRadius: radii.md, gap: spacing[3], paddingHorizontal: spacing[7], paddingVertical: spacing[8], width: '100%' },
    bootTitle: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 24, fontWeight: '700' },
    bootText: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 15, textAlign: 'center' },
    loginScreen: { backgroundColor: colors.canvas, flex: 1 },
    loginContainer: { backgroundColor: colors.canvas, flex: 1, minHeight: 0 },
    loginScroll: { flex: 1, minHeight: 0 },
    loginScrollContent: { alignItems: 'center', flexGrow: 1, justifyContent: 'center', width: '100%' },
    loginScrollContentMobile: { alignItems: 'stretch', justifyContent: 'flex-start' },
    loginLanguageRow: { alignItems: 'flex-end', position: 'absolute', right: spacing[6], top: spacing[6], zIndex: 30 },
    loginCard: { ...shadows.surface, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, overflow: 'visible', width: '100%' },
    loginCardMobile: { borderRadius: 0, borderWidth: 0, maxWidth: '100%' },
    loginCardWide: { flexDirection: 'row' },
    loginShowcase: { gap: spacing[6], padding: spacing[7] },
    loginShowcaseWide: { justifyContent: 'space-between', maxWidth: 420, minHeight: 520, width: '46%' },
    loginShowcaseTopRow: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between', zIndex: 60 },
    loginShowcaseLanguage: { alignItems: 'flex-end', flex: 1, minWidth: 0, zIndex: 70 },
    loginMark: { alignItems: 'center', backgroundColor: colors.overlayOnBrand, borderRadius: radii.md, height: 64, justifyContent: 'center', width: 64 },
    loginHeaderText: { gap: spacing[2] },
    loginTitle: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 30, fontWeight: '700' },
    loginSubtitle: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 15, lineHeight: 22 },
    loginForm: { gap: spacing[4], paddingBottom: spacing[6], paddingHorizontal: spacing[6], paddingTop: spacing[6], position: 'relative' },
    loginFormWide: { flex: 1, justifyContent: 'center', paddingBottom: spacing[7], paddingHorizontal: spacing[8], paddingTop: 76 },
    field: { gap: spacing[2] },
    fieldCompact: { flex: 1, minWidth: 0 },
    fieldLabel: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    textInput: { backgroundColor: colors.surfaceSubtle, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontFamily: fonts.sans, fontSize: 16, minHeight: 52, paddingHorizontal: spacing[4], paddingVertical: spacing[3] },
    passwordWrapper: { position: 'relative' },
    passwordInput: { paddingRight: 54 },
    passwordToggle: { alignItems: 'center', height: 52, justifyContent: 'center', position: 'absolute', right: 0, top: 0, width: 52 },
    primaryButton: { alignItems: 'center', backgroundColor: colors.brand, borderRadius: radii.md, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', minHeight: 54, paddingHorizontal: spacing[5] },
    primaryButtonDisabled: { opacity: 0.5 },
    primaryButtonPressed: { opacity: 0.85, transform: [{ scale: 0.98 }] },
    primaryButtonText: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700' },
    languageSelector: { maxWidth: 240, minWidth: 210, position: 'relative', zIndex: 40 },
    languageSelectorCompact: { minWidth: 186 },
    languageSelectorButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 48, paddingHorizontal: 12, paddingVertical: 8 },
    languageSelectorButtonOnBrand: { backgroundColor: colors.overlayOnBrand, borderColor: colors.overlayBorderOnBrand },
    languageFlag: { borderColor: 'rgba(11,28,48,0.16)', borderRadius: 4, borderWidth: 1, height: 20, overflow: 'hidden', position: 'relative', width: 30 },
    languageFlagHorizontal: { borderColor: 'rgba(11,28,48,0.16)', borderRadius: 4, borderWidth: 1, flexDirection: 'row', height: 20, overflow: 'hidden', width: 30 },
    languageFlagBrazil: { alignItems: 'center', backgroundColor: '#009739', justifyContent: 'center' },
    languageFlagBrazilDiamond: { backgroundColor: '#ffdf00', height: 15, position: 'absolute', transform: [{ rotate: '45deg' }], width: 15 },
    languageFlagBrazilCircle: { backgroundColor: '#002776', borderRadius: 5, height: 10, position: 'absolute', width: 10 },
    languageFlagUsCanton: { backgroundColor: '#3c3b6e', height: 11, left: 0, position: 'absolute', top: 0, width: 13, zIndex: 2 },
    languageFlagUsStripeRed: { backgroundColor: '#b22234', flex: 1 },
    languageFlagUsStripeWhite: { backgroundColor: '#ffffff', flex: 1 },
    languageFlagSpainRed: { backgroundColor: '#aa151b', flex: 1 },
    languageFlagSpainYellow: { backgroundColor: '#f1bf00', flex: 2 },
    languageFlagFranceBlue: { backgroundColor: '#0055a4', flex: 1 },
    languageFlagFranceWhite: { backgroundColor: '#ffffff', flex: 1 },
    languageFlagFranceRed: { backgroundColor: '#ef4135', flex: 1 },
    languageSelectorTextBlock: { flex: 1, minWidth: 0 },
    languageSelectorLabel: { color: '#414941', fontFamily: fonts.medium, fontSize: 10, fontWeight: '800', lineHeight: 13, textTransform: 'uppercase' },
    languageSelectorLabelOnBrand: { color: colors.brandMuted },
    languageSelectorValue: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 14, fontWeight: '800', lineHeight: 19 },
    languageSelectorValueOnBrand: { color: colors.inverseText },
    languageSelectorMenu: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 12, borderWidth: 1, elevation: 30, gap: 2, left: 0, padding: 6, position: 'absolute', right: 0, shadowColor: '#000000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 18, top: 54, zIndex: 80 },
    languageSelectorOption: { alignItems: 'center', borderRadius: 10, flexDirection: 'row', gap: 10, minHeight: 44, paddingHorizontal: 10, paddingVertical: 7 },
    languageSelectorOptionActive: { backgroundColor: '#ffffff' },
    languageSelectorOptionText: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 14, fontWeight: '800', lineHeight: 19 },
    languageSelectorOptionTextActive: { color: '#003215' },
    languageSelectorOptionMeta: { color: '#707970', fontFamily: fonts.sans, fontSize: 12, lineHeight: 16 },
    headerShell: { alignSelf: 'stretch', backgroundColor: '#ffffff', width: '100%' },
    header: { alignItems: 'center', backgroundColor: '#ffffff', borderBottomColor: '#c0c9be', borderBottomWidth: 1, elevation: 0, flexDirection: 'row', gap: spacing[3], height: 64, justifyContent: 'space-between', paddingHorizontal: 16, shadowOpacity: 0, shadowRadius: 0, width: '100%' },
    headerIdentity: { alignItems: 'center', flexDirection: 'row', flex: 1, gap: spacing[3], minWidth: 0 },
    avatarBadge: { alignItems: 'center', backgroundColor: colors.brand, borderRadius: radii.md, height: 44, justifyContent: 'center', width: 44 },
    avatarBadgeText: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700' },
    headerTextStack: { flex: 1, gap: 2 },
    headerBrandTitle: { color: '#003215', flex: 1, fontFamily: fonts.medium, fontSize: 28, fontWeight: '800', lineHeight: 36 },
    headerTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 24 },
    headerSubtitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 13, fontWeight: '600', lineHeight: 18 },
    headerActions: { alignItems: 'center', flexDirection: 'row', gap: spacing[2] },
    headerNotificationButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: radii.pill, borderWidth: 1, height: 44, justifyContent: 'center', width: 44 },
    chatHistoryDismissLayer: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 64, zIndex: 29 },
    chatHistorySidebar: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 8, borderWidth: 1, elevation: 24, gap: 12, left: 12, maxWidth: 360, padding: 14, position: 'absolute', shadowColor: '#101828', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.12, shadowRadius: 24, top: 76, width: '82%', zIndex: 30 },
    chatHistoryTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: '800', lineHeight: 20 },
    chatHistoryList: { gap: 8 },
    chatHistoryItem: { backgroundColor: colors.surfaceSubtle, borderColor: colors.border, borderRadius: 8, borderWidth: 1, gap: 2, minHeight: 58, paddingHorizontal: 12, paddingVertical: 10 },
    chatHistoryItemTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 14, fontWeight: '800', lineHeight: 19 },
    chatHistoryItemMeta: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 12, lineHeight: 16 },
    iconButton: { alignItems: 'center', backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, height: 42, justifyContent: 'center', width: 42 },
    desktopNav: { alignSelf: 'stretch', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', flexWrap: 'nowrap', gap: spacing[2], padding: spacing[2] },
    desktopFloatingNav: { ...shadows.surface, alignSelf: 'center', width: '100%' },
    desktopBottomNavShell: { alignItems: 'center', position: 'absolute', zIndex: 10 },
    aiLaunchOverlay: { alignItems: 'center', bottom: 0, left: 0, paddingBottom: 16, paddingHorizontal: 16, position: 'absolute', right: 0, zIndex: 40 },
    aiLaunchBarDesktop: { maxWidth: 640 },
    aiLaunchPromptContent: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 10, minWidth: 0 },
    desktopNavItem: { alignItems: 'center', borderRadius: radii.sm, flex: 1, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', minHeight: 46, paddingHorizontal: spacing[3] },
    desktopNavItemActive: { backgroundColor: colors.brandDark },
    desktopNavText: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 14, fontWeight: '700' },
    desktopNavTextActive: { color: colors.inverseText },
    sidebarLayout: { flex: 1, flexDirection: 'row', minHeight: 0 },
    sidebar: { backgroundColor: '#ffffff', borderRightColor: '#c0c9be', borderRightWidth: 1, gap: spacing[5], paddingHorizontal: 16, paddingTop: 18, width: 248 },
    sidebarBrand: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], minHeight: 52 },
    sidebarLogo: { alignItems: 'center', backgroundColor: colors.brandDark, borderRadius: radii.md, height: 44, justifyContent: 'center', width: 44 },
    sidebarBrandText: { flex: 1, minWidth: 0 },
    sidebarTitle: { color: colors.brandDark, fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 26 },
    sidebarSubtitle: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 12, lineHeight: 16 },
    sidebarNav: { gap: spacing[2] },
    sidebarNavItem: { alignItems: 'center', borderRadius: radii.md, flexDirection: 'row', gap: spacing[3], minHeight: 48, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    sidebarNavItemActive: { backgroundColor: colors.brandDark },
    sidebarNavText: { color: colors.textMuted, flex: 1, fontFamily: fonts.medium, fontSize: 15, fontWeight: '700' },
    sidebarNavTextActive: { color: colors.inverseText },
    sidebarMain: { flex: 1, minHeight: 0, minWidth: 0 },
    sidebarHeader: { alignItems: 'center', backgroundColor: '#ffffff', borderBottomColor: '#c0c9be', borderBottomWidth: 1, flexDirection: 'row', height: 64, justifyContent: 'space-between', paddingHorizontal: 24 },
    content: { gap: spacing[4], paddingHorizontal: spacing[5], paddingTop: 0 },
    contentShell: { alignSelf: 'center', gap: spacing[4], width: '100%' },
    errorBanner: { alignItems: 'center', backgroundColor: colors.dangerSubtle, borderColor: colors.dangerBorder, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between', paddingHorizontal: spacing[3], paddingVertical: spacing[3] },
    errorText: { color: colors.danger, flex: 1, fontFamily: fonts.medium, fontSize: 14, fontWeight: '600' },
    errorRetryButton: { backgroundColor: colors.danger, borderRadius: radii.pill, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    errorRetryText: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    sectionStack: { gap: spacing[4] },
    notificationsPage: { alignSelf: 'center', gap: 32, maxWidth: 760, paddingTop: 24, width: '100%' },
    notificationsTopRow: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
    notificationsTitleRow: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 12, minWidth: 0 },
    notificationsMenuIcon: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: radii.pill, borderWidth: 1, height: 42, justifyContent: 'center', width: 42 },
    notificationsTitle: { color: '#004b23', flex: 1, fontFamily: fonts.medium, fontSize: 26, fontWeight: '800', lineHeight: 34 },
    notificationsReadButton: { alignItems: 'center', borderRadius: 12, flexDirection: 'row', gap: 6, paddingHorizontal: 10, paddingVertical: 8 },
    notificationsReadButtonText: { color: '#003215', fontFamily: fonts.medium, fontSize: 13, fontWeight: '800', lineHeight: 18 },
    notificationsSection: { gap: 14 },
    notificationsSectionLabel: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', letterSpacing: 0, lineHeight: 14, textTransform: 'uppercase' },
    notificationsEmptyCard: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.95)', borderColor: '#c1c9bf', borderRadius: 16, borderWidth: 1, gap: 10, minHeight: 260, justifyContent: 'center', padding: 28 },
    notificationsEmptyIcon: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: radii.pill, borderWidth: 1, height: 96, justifyContent: 'center', marginBottom: 4, width: 96 },
    notificationsEmptyTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 22, fontWeight: '800', lineHeight: 30, textAlign: 'center' },
    notificationsEmptyText: { color: '#414941', fontFamily: fonts.sans, fontSize: 16, lineHeight: 24, maxWidth: 360, textAlign: 'center' },
    notificationsHintCard: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.78)', borderColor: 'rgba(193,201,191,0.7)', borderRadius: 16, borderWidth: 1, flexDirection: 'row', gap: 14, padding: 16 },
    notificationsHintIcon: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 12, borderWidth: 1, height: 48, justifyContent: 'center', width: 48 },
    notificationsHintText: { flex: 1, gap: 2, minWidth: 0 },
    notificationsHintTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 17, fontWeight: '800', lineHeight: 24 },
    notificationsHintDescription: { color: '#414941', fontFamily: fonts.sans, fontSize: 14, lineHeight: 20 },
    homeScreenStack: { gap: spacing[6] },
    homeHero: { alignItems: 'center', flexDirection: 'row', gap: spacing[4], paddingHorizontal: spacing[1], paddingTop: spacing[1] },
    homeHeroTextStack: { flex: 1, gap: 2, minWidth: 0 },
    homeGreetingTitle: { color: colors.brandDark, fontFamily: fonts.medium, fontSize: 28, fontWeight: '800', lineHeight: 34 },
    homeGreetingText: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 15, lineHeight: 21 },
    homeSection: { gap: spacing[3] },
    homeSectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: spacing[1] },
    homeSectionTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 26 },
    homeSectionAction: { color: colors.brand, fontFamily: fonts.medium, fontSize: 12, fontWeight: '800', letterSpacing: 0, textTransform: 'uppercase' },
    homeNextClassCard: { ...shadows.surface, backgroundColor: colors.brandDark, borderRadius: radii.md, gap: spacing[5], minHeight: 188, overflow: 'hidden', padding: spacing[5], position: 'relative' },
    homeNextClassWatermark: { position: 'absolute', right: -8, top: 10 },
    homeNextClassTop: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    homeNextClassBody: { flex: 1, gap: spacing[1], minWidth: 0 },
    homeNextClassCode: { color: colors.brandMuted, fontFamily: fonts.medium, fontSize: 12, fontWeight: '800', letterSpacing: 0, textTransform: 'uppercase' },
    homeNextClassTitle: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 23, fontWeight: '800', lineHeight: 29 },
    homeNextClassText: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 14, lineHeight: 20 },
    homeTimePill: { backgroundColor: colors.brand, borderRadius: radii.pill, flexShrink: 0, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    homeTimePillText: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 11, fontWeight: '800' },
    homeTeacherRow: { alignItems: 'center', flexDirection: 'row', gap: spacing[3] },
    homeTeacherAvatar: { alignItems: 'center', backgroundColor: colors.overlayOnBrand, borderColor: colors.overlayBorderOnBrand, borderRadius: radii.pill, borderWidth: 1, height: 42, justifyContent: 'center', width: 42 },
    homeTeacherText: { flex: 1, gap: 2, minWidth: 0 },
    homeTeacherName: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 15, fontWeight: '700' },
    homeTeacherMeta: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 13 },
    homeKpiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] },
    homeKpiCard: { ...shadows.surface, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flex: 1, gap: 3, minWidth: 100, overflow: 'hidden', paddingHorizontal: spacing[3], paddingVertical: spacing[2], position: 'relative' },
    homeKpiAccent: { bottom: 0, left: 0, position: 'absolute', top: 0, width: 3 },
    homeKpiTopRow: { alignItems: 'center', flexDirection: 'row', gap: 6 },
    homeKpiIconBadge: { alignItems: 'center', borderRadius: radii.pill, height: 20, justifyContent: 'center', width: 20 },
    homeKpiTonePrimary: { backgroundColor: colors.brandSubtle },
    homeKpiToneWarning: { backgroundColor: colors.warningSubtle },
    homeKpiToneDanger: { backgroundColor: colors.dangerSubtle },
    homeKpiLabel: { color: colors.textMuted, flexShrink: 1, fontFamily: fonts.medium, fontSize: 10.5, fontWeight: '800', letterSpacing: 0, textTransform: 'uppercase' },
    homeKpiValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 23 },
    homeKpiHint: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 10.5, lineHeight: 13 },
    homeProgressTrack: { backgroundColor: colors.surfaceMuted, borderRadius: radii.pill, height: 5, overflow: 'hidden', width: '100%' },
    homeProgressFillPrimary: { backgroundColor: colors.brand, borderRadius: radii.pill, height: '100%' },
    homeProgressFillWarning: { backgroundColor: colors.warning, borderRadius: radii.pill, height: '100%' },
    homeProgressCard: { ...shadows.surface, alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: spacing[4], padding: spacing[5] },
    homeProgressTextStack: { flex: 1, gap: spacing[1], minWidth: 140 },
    progressRingCenter: { alignItems: 'center', justifyContent: 'center' },
    homeProgressRingValue: { color: colors.brandDark, fontFamily: fonts.medium, fontSize: 22, fontWeight: '800' },
    homeAiCta: { ...shadows.surface, borderRadius: radii.md, elevation: 10, overflow: 'hidden', position: 'relative', shadowColor: '#0B3D32', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.22, shadowRadius: 20 },
    homeAiCtaGradient: { flexDirection: 'row', alignItems: 'center', gap: spacing[4], padding: spacing[5] },
    homeAiCtaGlow: { position: 'absolute', right: -20, top: -30 },
    homeAiCtaShine: { backgroundColor: 'rgba(255,255,255,0.32)', bottom: -30, position: 'absolute', top: -30, transform: [{ rotate: '20deg' }], width: 60 },
    homeAiCtaIconBadge: { alignItems: 'center', backgroundColor: colors.overlayOnBrand, borderColor: colors.overlayBorderOnBrand, borderRadius: radii.pill, borderWidth: 1, height: 52, justifyContent: 'center', width: 52 },
    homeAiCtaTextStack: { flex: 1, gap: 2, minWidth: 0 },
    homeAiCtaEyebrowRow: { alignItems: 'center', flexDirection: 'row', gap: 6 },
    homeAiCtaEyebrow: { color: colors.brandMuted, fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', letterSpacing: 0, textTransform: 'uppercase' },
    homeAiCtaProBadge: { backgroundColor: '#febf31', borderRadius: radii.pill, paddingHorizontal: 6, paddingVertical: 1 },
    homeAiCtaProBadgeText: { color: '#3a2900', fontFamily: fonts.medium, fontSize: 9, fontWeight: '800', letterSpacing: 0.5 },
    homeAiCtaTitle: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 18, fontWeight: '800', lineHeight: 23 },
    homeAiCtaText: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 13, lineHeight: 18 },
    homeAiCtaArrow: { alignItems: 'center', backgroundColor: colors.overlayOnBrand, borderRadius: radii.pill, height: 36, justifyContent: 'center', width: 36 },
    homeInsightHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing[2] },
    homeStatRow: { alignItems: 'center', backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, flexDirection: 'row', gap: spacing[3], minHeight: 56, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    homeStatIconBadge: { alignItems: 'center', borderRadius: radii.pill, height: 36, justifyContent: 'center', width: 36 },
    homeStatTextStack: { flex: 1, gap: 1, minWidth: 0 },
    homeStatValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 17, fontWeight: '800' },
    homeStatLabel: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 12.5 },
    panel: { ...shadows.surface, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: spacing[4], padding: spacing[5] },
    panelHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    panelTitle: { ...typography.title, color: colors.text, flexShrink: 1 },
    panelDescription: { ...typography.body, color: colors.textMuted },
    sectionKicker: { ...typography.eyebrow, color: colors.brand, textTransform: 'uppercase' },
    metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] },
    metricGridWide: { justifyContent: 'space-between' },
    metricCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexBasis: '47%', flexGrow: 1, gap: spacing[2], minHeight: 90, padding: spacing[4] },
    metricSkeletonItem: { flexBasis: '47%', flexGrow: 1 },
    tileLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    tileValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: '600' },
    metricValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 30, fontWeight: '700' },
    twoColumnGrid: { gap: spacing[4] },
    highlightCard: { backgroundColor: colors.brandSubtle, borderRadius: radii.md, gap: spacing[2], padding: spacing[4] },
    highlightLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    highlightTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    highlightText: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 14 },
    highlightTime: { color: colors.brand, fontFamily: fonts.medium, fontSize: 30, fontWeight: '700', marginTop: spacing[2] },
    weekChart: { alignItems: 'flex-end', flexDirection: 'row', gap: spacing[2], justifyContent: 'space-between', minHeight: 140 },
    weekBarItem: { alignItems: 'center', flex: 1, gap: spacing[2] },
    weekBarTrack: { alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radii.md, flex: 1, justifyContent: 'flex-end', minHeight: 100, overflow: 'hidden', padding: spacing[1], width: '100%' },
    weekBarFill: { backgroundColor: colors.brand, borderRadius: radii.sm, width: '100%' },
    weekBarLabel: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    weekBarValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    gradeSummaryBoard: { gap: spacing[5] },
    gradeRing: { alignItems: 'center', alignSelf: 'center', backgroundColor: colors.brandSubtle, borderColor: colors.brandMuted, borderRadius: radii.pill, borderWidth: 12, height: 150, justifyContent: 'center', width: 150 },
    gradeRingValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 34, fontWeight: '700' },
    gradeRingLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    gradeStatStack: { gap: spacing[2] },
    statPill: { backgroundColor: colors.surfaceMuted, borderRadius: radii.md, gap: spacing[1], paddingHorizontal: spacing[3], paddingVertical: spacing[3] },
    statPillValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 20, fontWeight: '700' },
    listStack: { gap: spacing[3] },
    attentionCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[1], padding: spacing[3] },
    attentionTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700' },
    attentionCardRow: { alignItems: 'center', flexDirection: 'row', gap: spacing[3] },
    attentionCardBody: { flex: 1, gap: 2, minWidth: 0 },
    attentionCardDanger: { borderLeftColor: colors.danger, borderLeftWidth: 3 },
    attentionCardWarning: { borderLeftColor: colors.warning, borderLeftWidth: 3 },
    attentionBadge: { alignItems: 'center', borderRadius: radii.pill, flexShrink: 0, height: 32, justifyContent: 'center', width: 32 },
    attentionGradeBadge: { alignItems: 'center', borderRadius: radii.md, flexShrink: 0, minWidth: 54, paddingHorizontal: spacing[2], paddingVertical: 6 },
    attentionGradeLabel: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 9.5, fontWeight: '800', letterSpacing: 0, textTransform: 'uppercase' },
    attentionGradeValue: { color: colors.brand, fontFamily: fonts.medium, fontSize: 17, fontWeight: '800', lineHeight: 20 },
    attentionTextDanger: { color: colors.danger },
    attentionTextWarning: { color: colors.warning },
    profileHero: { alignItems: 'center', flexDirection: 'row', gap: spacing[4], padding: spacing[5] },
    profileAvatar: { alignItems: 'center', backgroundColor: colors.brandMuted, borderRadius: radii.md, height: 68, justifyContent: 'center', width: 68 },
    profileAvatarText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 24, fontWeight: '700' },
    profileHeroText: { flex: 1, gap: spacing[2], minWidth: 0 },
    profilePage: { alignSelf: 'center', maxWidth: 1280, width: '100%' },
    profileCover: { backgroundColor: '#003215', borderBottomLeftRadius: 18, borderBottomRightRadius: 18, marginHorizontal: -18, minHeight: 294, overflow: 'hidden', paddingBottom: 70, paddingHorizontal: 20, paddingTop: 42, position: 'relative' },
    profileGridTexture: { backgroundColor: 'rgba(255,255,255,0.07)', borderColor: 'rgba(255,255,255,0.08)', borderWidth: 1, bottom: 18, left: 18, opacity: 0.75, position: 'absolute', right: 18, top: 18 },
    profileCoverContent: { alignItems: 'center', zIndex: 1 },
    profileLargeAvatarWrap: { marginBottom: 18, position: 'relative' },
    profileLargeAvatar: { alignItems: 'center', backgroundColor: '#eef7f3', borderColor: 'rgba(255,255,255,0.28)', borderRadius: 58, borderWidth: 4, height: 116, justifyContent: 'center', shadowOpacity: 0, shadowRadius: 0, width: 116 },
    profileLargeAvatarText: { color: '#003215', fontFamily: fonts.medium, fontSize: 36, fontWeight: '800' },
    profileStatusDot: { backgroundColor: '#79bb87', borderColor: '#ffffff', borderRadius: 12, borderWidth: 3, bottom: 6, height: 24, position: 'absolute', right: 6, width: 24 },
    profileName: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 28, fontWeight: '600', lineHeight: 36, marginBottom: 4, textAlign: 'center' },
    profileCourse: { color: '#bcefc3', fontFamily: fonts.medium, fontSize: 17, fontWeight: '600', lineHeight: 24, marginBottom: 18, textAlign: 'center' },
    profilePillRow: { flexDirection: 'row', gap: 8 },
    profileHeroPill: { backgroundColor: 'rgba(255,255,255,0.12)', borderColor: 'rgba(255,255,255,0.24)', borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 6 },
    profileHeroPillText: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 11, fontWeight: '500', letterSpacing: 0, lineHeight: 14, textTransform: 'uppercase' },
    profileContentStack: { gap: 14, marginTop: -34, paddingBottom: 20, paddingHorizontal: 16, position: 'relative', zIndex: 2 },
    profileGlassCard: { backgroundColor: '#ffffff', borderColor: '#c1c9bf', borderRadius: 14, borderWidth: 1, elevation: 0, overflow: 'hidden', padding: 20, shadowOpacity: 0, shadowRadius: 0 },
    profileSectionHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
    profileSectionIcon: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c1c9bf', borderRadius: radii.pill, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
    profileSectionTitle: { color: '#001b08', flex: 1, fontFamily: fonts.medium, fontSize: 19, fontWeight: '700', lineHeight: 26 },
    profileAcademicGrid: { gap: 10, marginTop: 16 },
    profileInfoBlock: { backgroundColor: '#ffffff', borderColor: '#d8e1d6', borderRadius: 10, borderWidth: 1, gap: 6, padding: 14 },
    profileInfoLabelRow: { alignItems: 'center', flexDirection: 'row', gap: 6 },
    profileInfoLabel: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '700', letterSpacing: 0, lineHeight: 14, textTransform: 'uppercase' },
    profileInfoValue: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 16, fontWeight: '700', lineHeight: 22 },
    profileCardHeader: { paddingBottom: 16 },
    profileListRow: { alignItems: 'center', borderTopColor: '#d8e1d6', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: -20, paddingHorizontal: 20, paddingVertical: 18 },
    profileListRowBody: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 14, minWidth: 0 },
    profileListIcon: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d8e1d6', borderRadius: radii.pill, borderWidth: 1, height: 44, justifyContent: 'center', width: 44 },
    profileListText: { flex: 1, minWidth: 0 },
    profileListLabel: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '700', lineHeight: 14, textTransform: 'uppercase' },
    profileListValue: { color: '#0b1c30', fontFamily: fonts.sans, fontSize: 16, lineHeight: 22 },
    profileActions: { gap: 14, paddingTop: 10 },
    profilePrimaryAction: { alignItems: 'center', backgroundColor: '#001b08', borderRadius: 12, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 60 },
    profilePrimaryActionText: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 20, fontWeight: '600', lineHeight: 28 },
    profileDangerAction: { alignItems: 'center', backgroundColor: '#fff7f6', borderColor: '#f1b8b3', borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 54 },
    profileDangerActionText: { color: '#ba1a1a', fontFamily: fonts.medium, fontSize: 18, fontWeight: '700', lineHeight: 26 },
    infoTile: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexBasis: '47%', flexGrow: 1, gap: spacing[2], minHeight: 90, padding: spacing[4] },
    detailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] },
    detailCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, flexBasis: '47%', flexGrow: 1, gap: spacing[2], minHeight: 90, padding: spacing[4] },
    detailValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: '600' },
    scheduleHero: { gap: spacing[4] },
    scheduleHeroText: { gap: spacing[2] },
    timeBadge: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.infoSubtle, borderRadius: radii.md, flexDirection: 'row', gap: spacing[2], paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    timeBadgeText: { color: colors.info, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    chipsRow: { marginBottom: spacing[2] },
    weekChip: { alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radii.pill, flexDirection: 'row', gap: spacing[2], marginRight: spacing[2], paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    weekChipActive: { backgroundColor: colors.brandMuted },
    weekChipText: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    weekChipTextActive: { color: colors.brand },
    weekChipNumber: { color: colors.text, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    laneCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[3], padding: spacing[4] },
    laneHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    scheduleEvent: { borderRadius: radii.md, flexDirection: 'row', gap: spacing[3], padding: spacing[3] },
    eventToneGreen: { backgroundColor: colors.successSubtle },
    eventToneBlue: { backgroundColor: colors.infoSubtle },
    eventToneAmber: { backgroundColor: colors.warningSubtle },
    eventToneCoral: { backgroundColor: colors.dangerSubtle },
    schedulePage: { gap: 24, marginHorizontal: -18 },
    scheduleDaySelector: { backgroundColor: '#ffffff', borderBottomColor: 'rgba(192,201,190,0.55)', borderBottomWidth: 1, elevation: 0, flexDirection: 'row', gap: 8, justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 16, shadowOpacity: 0, shadowRadius: 0, zIndex: 5 },
    scheduleDayButton: { alignItems: 'center', borderRadius: 8, flex: 1, minHeight: 60, paddingHorizontal: 4, paddingVertical: 8, position: 'relative' },
    scheduleDayButtonActive: { backgroundColor: '#ffffff' },
    scheduleDayLabel: { color: '#404941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '500', lineHeight: 14 },
    scheduleDayNumber: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 20, fontWeight: '600', lineHeight: 28 },
    scheduleDayNumberActive: { color: '#003215' },
    scheduleDayIndicator: { backgroundColor: '#004b23', borderRadius: radii.pill, bottom: -2, height: 3, left: '20%', position: 'absolute', right: '20%' },
    scheduleTimeline: { marginHorizontal: 16, paddingLeft: 0, position: 'relative' },
    scheduleTimelineLine: { backgroundColor: '#c0c9be', bottom: 190, left: 19, opacity: 0.55, position: 'absolute', top: 0, width: 2 },
    scheduleTimelineItem: { flexDirection: 'row', gap: 16, marginBottom: 24, position: 'relative', zIndex: 1 },
    scheduleTimelineMarkerColumn: { alignItems: 'center', paddingTop: 8, width: 40 },
    scheduleTimelineMarker: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#ffffff', borderRadius: radii.pill, borderWidth: 4, height: 40, justifyContent: 'center', width: 40 },
    scheduleTimelineMarkerActive: { backgroundColor: '#004b23' },
    scheduleClassCard: { backgroundColor: '#ffffff', borderColor: 'rgba(192,201,190,0.2)', borderRadius: 8, borderWidth: 1, elevation: 0, flex: 1, padding: 16, shadowOpacity: 0, shadowRadius: 0 },
    scheduleClassHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between', marginBottom: 8 },
    scheduleClassTitleBlock: { flex: 1, gap: 4, minWidth: 0 },
    scheduleClassCodeBadge: { alignSelf: 'flex-start', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 4, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 2 },
    scheduleClassCodeText: { color: '#404941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '500', lineHeight: 14 },
    scheduleClassTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 20, fontWeight: '600', lineHeight: 28 },
    scheduleActiveBadge: { backgroundColor: 'rgba(174,242,187,0.5)', borderRadius: 4, paddingHorizontal: 8, paddingVertical: 4 },
    scheduleActiveBadgeText: { color: '#003215', fontFamily: fonts.medium, fontSize: 11, fontWeight: '500', lineHeight: 14 },
    scheduleClassMeta: { gap: 8, marginTop: 12 },
    scheduleMetaRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
    scheduleMetaText: { color: '#404941', fontFamily: fonts.sans, fontSize: 16, lineHeight: 24 },
    scheduleLunchMarkerColumn: { opacity: 0.5, paddingTop: 4 },
    scheduleLunchMarker: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#ffffff', borderRadius: radii.pill, borderWidth: 4, height: 40, justifyContent: 'center', width: 40 },
    scheduleLunchContent: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 12, paddingVertical: 8 },
    scheduleLunchLine: { backgroundColor: 'rgba(192,201,190,0.3)', flex: 1, height: 1 },
    scheduleLunchText: { color: '#707970', flexShrink: 0, fontFamily: fonts.medium, fontSize: 11, fontStyle: 'italic', fontWeight: '500', lineHeight: 14 },
    scheduleTipCard: { backgroundColor: '#febf31', borderRadius: 8, marginBottom: 16, marginTop: 24, minHeight: 190, overflow: 'hidden', padding: 24, position: 'relative' },
    scheduleTipContent: { alignItems: 'flex-start', gap: 8, maxWidth: 310, zIndex: 1 },
    scheduleTipHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, marginBottom: 0 },
    scheduleTipLabel: { color: '#6e4f00', fontFamily: fonts.medium, fontSize: 13, fontWeight: '500', lineHeight: 16 },
    scheduleTipText: { color: '#6e4f00', fontFamily: fonts.medium, fontSize: 20, fontWeight: '600', lineHeight: 28 },
    scheduleTipButton: { backgroundColor: 'rgba(255,255,255,0.6)', borderRadius: radii.pill, marginTop: 16, paddingHorizontal: 16, paddingVertical: 8 },
    scheduleTipButtonText: { color: '#6e4f00', fontFamily: fonts.medium, fontSize: 11, fontWeight: '500', lineHeight: 14 },
    scheduleTipIcon: { bottom: -24, opacity: 0.8, position: 'absolute', right: -16 },
    eventTimeBox: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radii.md, justifyContent: 'center', minHeight: 64, paddingHorizontal: spacing[3], width: 88 },
    eventTimePrimary: { color: colors.text, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    eventTimeSecondary: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 12 },
    eventBody: { flex: 1, gap: spacing[1], minWidth: 0 },
    smallCaps: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    eventTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700', lineHeight: 21 },
    eventSubtitle: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 13 },
    bigNumber: { color: colors.text, fontFamily: fonts.medium, fontSize: 48, fontWeight: '700' },
    gradeOverviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
    inputRow: { alignItems: 'flex-end', flexDirection: 'row', gap: spacing[2] },
    inputRowWide: { alignItems: 'stretch' },
    gradeCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[4], padding: spacing[4] },
    gradeHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    gradeHeaderText: { flex: 1, gap: spacing[1], minWidth: 0 },
    statusPill: { borderRadius: radii.pill, flexShrink: 1, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    statusOk: { backgroundColor: colors.successSubtle },
    statusWarn: { backgroundColor: colors.warningSubtle },
    statusDanger: { backgroundColor: colors.dangerSubtle },
    statusPillText: { color: colors.text, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    horizontalList: { marginHorizontal: -2 },
    evaluationCard: { backgroundColor: colors.surface, borderRadius: radii.md, gap: spacing[2], marginRight: spacing[2], padding: spacing[4], width: 138 },
    evaluationBadge: { alignItems: 'center', backgroundColor: colors.brandMuted, borderRadius: radii.sm, height: 28, justifyContent: 'center', width: 28 },
    evaluationBadgeText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    evaluationScore: { color: colors.text, fontFamily: fonts.medium, fontSize: 26, fontWeight: '700' },
    miniGradeCard: { backgroundColor: colors.surface, borderRadius: radii.md, flexBasis: '47%', flexGrow: 1, gap: spacing[2], padding: spacing[4] },
    miniGradeCardFeatured: { backgroundColor: colors.brandMuted },
    miniGradeValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 24, fontWeight: '700' },
    miniGradeValueFeatured: { color: colors.brand },
    subjectChip: { backgroundColor: colors.surfaceMuted, borderRadius: radii.md, gap: spacing[1], marginRight: spacing[2], paddingHorizontal: spacing[3], paddingVertical: spacing[3], width: 176 },
    subjectChipActive: { backgroundColor: colors.brandDark },
    subjectChipCode: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    subjectChipCodeActive: { color: colors.brandMuted },
    subjectChipText: { color: colors.text, fontFamily: fonts.medium, fontSize: 14, fontWeight: '600' },
    subjectChipTextActive: { color: colors.inverseText },
    coursesScreenStack: { alignSelf: 'center', gap: 32, maxWidth: 768, overflow: 'visible', paddingTop: 24, position: 'relative', width: '100%' },
    coursesHero: { gap: 6, overflow: 'visible', position: 'relative', zIndex: 400 },
    coursesTitle: { color: '#003215', fontFamily: fonts.medium, fontSize: 24, fontWeight: '800', lineHeight: 32 },
    coursesCourseText: { color: '#404941', fontFamily: fonts.sans, fontSize: 16, lineHeight: 22 },
    coursesPeriodCard: { display: 'none' },
    coursesPeriodSummary: { display: 'none' },
    coursesPeriodKicker: { display: 'none' },
    coursesPeriodTitle: { display: 'none' },
    coursesMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4, marginTop: 2 },
    coursesMetaChip: { alignItems: 'center', backgroundColor: '#eef3ec', borderRadius: 999, flexDirection: 'row', gap: 6, paddingHorizontal: 12, paddingVertical: 6 },
    coursesMetaChipText: { color: '#003215', fontFamily: fonts.medium, fontSize: 12.5, fontWeight: '700' },
    coursesSelectorRow: { flexDirection: 'row', gap: 12, marginTop: 6, overflow: 'visible', zIndex: 110 },
    coursesSelectorColumn: { flex: 1, gap: 6, overflow: 'visible', position: 'relative', zIndex: 120 },
    coursesSelectorLabel: { color: '#404941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14, textTransform: 'uppercase' },
    coursesSelectorButton: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 8, borderWidth: 1, minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 },
    coursesSelectorValue: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 14, fontWeight: '800', lineHeight: 20 },
    coursesOptionsPanel: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 8, borderWidth: 1, elevation: 80, left: 0, maxHeight: 220, overflow: 'hidden', position: 'absolute', right: 0, shadowOpacity: 0, shadowRadius: 0, top: 66, zIndex: 900 },
    coursesOptionItem: { minHeight: 40, justifyContent: 'center', paddingHorizontal: 12 },
    coursesOptionItemActive: { backgroundColor: '#003215' },
    coursesOptionText: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    coursesOptionTextActive: { color: '#ffffff' },
    coursesList: { elevation: 0, gap: 16, position: 'relative', zIndex: 0 },
    courseCard: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 12, borderWidth: 1, elevation: 0, gap: 16, padding: 16, position: 'relative', shadowColor: '#000000', shadowOpacity: 0.04, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, zIndex: 0 },
    courseCardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 16, justifyContent: 'space-between', marginBottom: 0 },
    courseCardTitleBlock: { flex: 1, gap: 8, minWidth: 0 },
    courseCodeBadge: { alignSelf: 'flex-start', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 4, borderWidth: 1, marginBottom: 2, paddingHorizontal: 8, paddingVertical: 2 },
    courseCodeBadgeDanger: { backgroundColor: 'rgba(255,218,214,0.24)' },
    courseCodeText: { color: '#404941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', letterSpacing: 0, lineHeight: 14, textTransform: 'uppercase' },
    courseCodeTextDanger: { color: '#ba1a1a' },
    courseSubjectTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 28 },
    courseGradeBlock: { alignItems: 'flex-end', flexShrink: 0 },
    courseGradeValue: { fontFamily: fonts.medium, fontSize: 24, fontWeight: '800', lineHeight: 32 },
    courseGradeLabel: { color: '#404941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14 },
    courseFrequencyBlock: { gap: 4 },
    courseFrequencyHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 0 },
    courseMetaLabel: { color: '#404941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14 },
    courseFrequencyValue: { fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14 },
    courseProgressTrack: { backgroundColor: 'rgba(0,50,21,0.1)', borderRadius: radii.pill, height: 6, overflow: 'hidden' },
    courseProgressTrackDanger: { backgroundColor: 'rgba(255,218,214,0.3)' },
    courseProgressTrackUnavailable: { backgroundColor: '#ffffff' },
    courseProgressFill: { backgroundColor: '#003215', borderRadius: radii.pill, height: '100%' },
    courseProgressFillDanger: { backgroundColor: '#ba1a1a' },
    courseProgressFillUnavailable: { backgroundColor: '#c0c9be', opacity: 0.55 },
    courseRiskRow: { alignItems: 'center', flexDirection: 'row', gap: 4, paddingTop: 8 },
    courseRiskText: { color: '#ba1a1a', fontFamily: fonts.medium, fontSize: 11, fontWeight: '700', lineHeight: 14 },
    courseFrequencyUnavailable: { color: '#707970', fontFamily: fonts.sans, fontSize: 11, lineHeight: 14, paddingTop: 6 },
    courseDetailPanel: { borderTopColor: '#c0c9be', borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginTop: 0, paddingTop: 16 },
    courseDetailColumn: { flex: 1, gap: 2, minWidth: 120 },
    courseDetailColumnRight: { alignItems: 'flex-end' },
    courseDetailFull: { flexBasis: '100%', gap: 2 },
    courseDetailText: { color: '#0b1c30', fontFamily: fonts.sans, fontSize: 14, lineHeight: 20 },
    courseStatusText: { fontFamily: fonts.medium, fontSize: 14, fontWeight: '600', lineHeight: 20 },
    courseDetailsPage: { alignSelf: 'center', gap: 24, maxWidth: 1120, paddingBottom: 24, width: '100%' },
    courseDetailsTopBar: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.95)', borderBottomColor: '#c1c9bf', borderBottomWidth: 1, flexDirection: 'row', gap: 12, justifyContent: 'space-between', marginHorizontal: -18, minHeight: 64, paddingHorizontal: 16 },
    courseDetailsIconButton: { alignItems: 'center', borderRadius: radii.pill, height: 42, justifyContent: 'center', width: 42 },
    courseDetailsHeaderTitle: { color: '#003215', flex: 1, fontFamily: fonts.medium, fontSize: 22, fontWeight: '700', lineHeight: 28 },
    courseDetailsHero: { backgroundColor: '#003215', borderRadius: 16, gap: 10, overflow: 'hidden', padding: 24, position: 'relative' },
    courseDetailsBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    courseDetailsCodeBadge: { backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: radii.pill, color: '#ffffff', fontFamily: fonts.medium, fontSize: 11, fontWeight: '700', lineHeight: 14, paddingHorizontal: 12, paddingVertical: 5, textTransform: 'uppercase' },
    courseDetailsSemesterBadge: { backgroundColor: '#febf31', borderRadius: radii.pill, color: '#6e4f00', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14, paddingHorizontal: 12, paddingVertical: 5, textTransform: 'uppercase' },
    courseDetailsTitle: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 34, fontWeight: '800', lineHeight: 42 },
    courseDetailsTeacherRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
    courseDetailsTeacher: { color: 'rgba(255,255,255,0.82)', flex: 1, fontFamily: fonts.sans, fontSize: 17, lineHeight: 24 },
    courseDetailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
    courseDetailsAverageCard: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.92)', borderColor: 'rgba(193,201,191,0.55)', borderRadius: 16, borderWidth: 1, flexGrow: 1, gap: 8, justifyContent: 'center', minHeight: 176, minWidth: 190, padding: 20 },
    courseDetailsEvaluationsCard: { backgroundColor: 'rgba(255,255,255,0.92)', borderColor: 'rgba(193,201,191,0.55)', borderRadius: 16, borderWidth: 1, flexBasis: Platform.OS === 'web' ? '58%' : '100%', flexGrow: 2, gap: 16, minWidth: 280, padding: 20 },
    courseDetailsKicker: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '700', lineHeight: 14, textTransform: 'uppercase' },
    courseDetailsAverageValue: { color: '#003215', fontFamily: fonts.medium, fontSize: 48, fontWeight: '800', lineHeight: 56 },
    courseDetailsStatusPill: { alignItems: 'center', borderRadius: radii.pill, flexDirection: 'row', gap: 6, paddingHorizontal: 12, paddingVertical: 5 },
    courseDetailsStatusOk: { backgroundColor: 'rgba(121,187,135,0.16)' },
    courseDetailsStatusNeutral: { backgroundColor: '#ffffff' },
    courseDetailsStatusText: { color: '#003215', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14, textTransform: 'uppercase' },
    courseDetailsSectionHeader: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
    courseDetailsSectionTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 8, minWidth: 0 },
    courseDetailsSectionTitle: { color: '#003215', flexShrink: 1, fontFamily: fonts.medium, fontSize: 20, fontWeight: '700', lineHeight: 28 },
    courseDetailsSeeAllButton: { alignItems: 'center', flexDirection: 'row', gap: 4, paddingHorizontal: 4, paddingVertical: 4 },
    courseDetailsSeeAllText: { color: '#003215', fontFamily: fonts.medium, fontSize: 13, fontWeight: '800', lineHeight: 18 },
    courseDetailsMutedText: { color: '#414941', fontFamily: fonts.sans, fontSize: 13, lineHeight: 18 },
    courseDetailsEmptyText: { color: '#414941', fontFamily: fonts.sans, fontSize: 15, lineHeight: 22 },
    courseDetailsEvaluationList: { gap: 14 },
    courseDetailsEvaluationRow: { alignItems: 'center', flexDirection: 'row', gap: 16, justifyContent: 'space-between' },
    courseDetailsEvaluationText: { flex: 1, minWidth: 0 },
    courseDetailsEvaluationName: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 16, fontWeight: '700', lineHeight: 22 },
    courseDetailsEvaluationScoreBlock: { alignItems: 'center', flexDirection: 'row', gap: 12 },
    courseDetailsEvaluationTrack: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: radii.pill, borderWidth: 1, height: 8, overflow: 'hidden', width: 110 },
    courseDetailsEvaluationFill: { backgroundColor: '#003215', borderRadius: radii.pill, height: '100%' },
    courseDetailsEvaluationWeight: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14 },
    courseDetailsEvaluationScore: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 8, borderWidth: 1, color: '#0b1c30', fontFamily: fonts.medium, fontSize: 13, fontWeight: '700', lineHeight: 18, minWidth: 44, paddingHorizontal: 10, paddingVertical: 5, textAlign: 'center' },
    courseDetailsInfoCard: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.92)', borderColor: 'rgba(193,201,191,0.55)', borderRadius: 16, borderWidth: 1, flexBasis: '31%', flexDirection: 'row', flexGrow: 1, gap: 12, minHeight: 84, minWidth: 220, padding: 16 },
    courseDetailsInfoIcon: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 12, borderWidth: 1, height: 42, justifyContent: 'center', width: 42 },
    courseDetailsInfoBody: { flex: 1, gap: 2, minWidth: 0 },
    courseDetailsInfoValue: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 17, fontWeight: '700', lineHeight: 24 },
    courseDetailsAbsenceCard: { borderRadius: 16, borderWidth: 1, flexBasis: '31%', flexGrow: 1, gap: 12, minHeight: 148, minWidth: 260, padding: 16 },
    courseDetailsAbsenceCardOk: { backgroundColor: 'rgba(121,187,135,0.12)', borderColor: 'rgba(0,50,21,0.18)' },
    courseDetailsAbsenceCardWarning: { backgroundColor: 'rgba(254,191,49,0.16)', borderColor: 'rgba(123,88,0,0.24)' },
    courseDetailsAbsenceCardAlert: { backgroundColor: 'rgba(255,218,214,0.35)', borderColor: 'rgba(186,26,26,0.26)' },
    courseDetailsAbsenceTop: { alignItems: 'center', flexDirection: 'row', gap: 10 },
    courseDetailsAbsenceIcon: { alignItems: 'center', borderRadius: 12, height: 46, justifyContent: 'center', width: 46 },
    courseDetailsAbsenceIconOk: { backgroundColor: 'rgba(0,50,21,0.1)' },
    courseDetailsAbsenceIconWarning: { backgroundColor: 'rgba(254,191,49,0.25)' },
    courseDetailsAbsenceIconAlert: { backgroundColor: 'rgba(186,26,26,0.1)' },
    courseDetailsAbsenceTitleBlock: { flex: 1, gap: 1, minWidth: 0 },
    courseDetailsAbsenceKicker: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14, textTransform: 'uppercase' },
    courseDetailsAbsenceTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 19, fontWeight: '800', lineHeight: 26 },
    courseDetailsAbsenceBadge: { borderRadius: radii.pill, flexShrink: 0, fontFamily: fonts.medium, fontSize: 10, fontWeight: '800', lineHeight: 13, paddingHorizontal: 8, paddingVertical: 3, textTransform: 'uppercase' },
    courseDetailsAbsenceBadgeOk: { backgroundColor: 'rgba(121,187,135,0.18)', color: '#003215' },
    courseDetailsAbsenceBadgeWarning: { backgroundColor: 'rgba(254,191,49,0.22)', color: '#6e4f00' },
    courseDetailsAbsenceBadgeAlert: { backgroundColor: 'rgba(255,218,214,0.55)', color: '#ba1a1a' },
    courseDetailsAbsenceNumbers: { alignItems: 'flex-end', flexDirection: 'row', justifyContent: 'space-between' },
    courseDetailsAbsenceNumber: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 30, fontWeight: '800', lineHeight: 36 },
    courseDetailsAbsenceLimitBox: { alignItems: 'flex-end' },
    courseDetailsAbsenceLimitValue: { color: '#414941', fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 26 },
    courseDetailsAbsenceNumberLabel: { color: '#414941', fontFamily: fonts.sans, fontSize: 12, lineHeight: 16 },
    courseDetailsAbsenceTrack: { backgroundColor: 'rgba(255,255,255,0.7)', borderRadius: radii.pill, height: 8, overflow: 'hidden' },
    courseDetailsAbsenceFill: { borderRadius: radii.pill, height: '100%' },
    courseDetailsAbsenceFillOk: { backgroundColor: '#003215' },
    courseDetailsAbsenceFillWarning: { backgroundColor: '#febf31' },
    courseDetailsAbsenceFillAlert: { backgroundColor: '#ba1a1a' },
    courseDetailsAbsenceDescription: { color: '#414941', fontFamily: fonts.sans, fontSize: 13, lineHeight: 18 },
    courseDetailsTimelineSection: { gap: 16 },
    courseDetailsTimeline: { gap: 14, position: 'relative' },
    courseDetailsTimelineItem: { flexDirection: 'row', gap: 12 },
    courseDetailsTimelineMarker: { alignItems: 'center', backgroundColor: '#003215', borderColor: '#ffffff', borderRadius: radii.pill, borderWidth: 4, height: 40, justifyContent: 'center', marginTop: 12, width: 40 },
    courseDetailsLessonCard: { backgroundColor: 'rgba(255,255,255,0.94)', borderColor: 'rgba(193,201,191,0.55)', borderRadius: 12, borderWidth: 1, flex: 1, gap: 6, padding: 16 },
    courseDetailsLessonHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
    courseDetailsLessonDate: { color: '#003215', fontFamily: fonts.medium, fontSize: 13, fontWeight: '800', lineHeight: 18 },
    courseDetailsLessonBadge: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: 6, borderWidth: 1, color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '700', lineHeight: 14, paddingHorizontal: 8, paddingVertical: 3 },
    courseDetailsLessonTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 18, fontWeight: '800', lineHeight: 25 },
    courseDetailsLessonText: { color: '#414941', fontFamily: fonts.sans, fontSize: 15, lineHeight: 22 },
    courseContentPage: { alignSelf: 'center', gap: 24, maxWidth: 980, paddingBottom: 24, width: '100%' },
    courseContentHero: { backgroundColor: '#003215', borderRadius: 16, gap: 8, overflow: 'hidden', padding: 24, position: 'relative' },
    courseContentCode: { color: 'rgba(188,239,195,0.82)', fontFamily: fonts.medium, fontSize: 13, fontWeight: '800', lineHeight: 18, textTransform: 'uppercase' },
    courseContentTitle: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 24, fontWeight: '800', lineHeight: 32 },
    courseContentProgressBlock: { gap: 8, marginTop: 18 },
    courseContentProgressHeader: { alignItems: 'flex-end', flexDirection: 'row', justifyContent: 'space-between' },
    courseContentProgressLabel: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 13, fontWeight: '700', lineHeight: 18 },
    courseContentProgressValue: { color: '#febf31', fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 28 },
    courseContentProgressTrack: { backgroundColor: '#001b08', borderColor: 'rgba(255,255,255,0.1)', borderRadius: radii.pill, borderWidth: 1, height: 12, overflow: 'hidden' },
    courseContentProgressFill: { backgroundColor: '#fbbc2e', borderRadius: radii.pill, height: '100%' },
    courseContentProgressHint: { color: 'rgba(255,255,255,0.72)', fontFamily: fonts.sans, fontSize: 13, lineHeight: 18 },
    courseContentTabs: { flexDirection: 'row', gap: 10, marginHorizontal: -2, overflow: 'visible', paddingHorizontal: 2 },
    courseContentTab: { backgroundColor: '#ffffff', borderColor: '#c0c9be', borderRadius: radii.pill, borderWidth: 1, color: '#414941', fontFamily: fonts.medium, fontSize: 13, fontWeight: '700', lineHeight: 18, paddingHorizontal: 16, paddingVertical: 8 },
    courseContentTabActive: { backgroundColor: '#001b08', color: '#ffffff' },
    courseContentSection: { gap: 16 },
    courseContentSectionTitle: { color: '#003215', fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 28, textTransform: 'uppercase' },
    courseContentList: { gap: 14 },
    courseContentLessonCard: { backgroundColor: 'rgba(255,255,255,0.96)', borderColor: '#c1c9bf', borderLeftColor: '#febf31', borderLeftWidth: 4, borderRadius: 16, borderWidth: 1, overflow: 'hidden' },
    courseContentCardInner: { gap: 12, padding: 18 },
    courseContentCardUpcoming: { backgroundColor: 'rgba(255,255,255,0.96)' },
    courseContentLessonHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
    courseContentLessonHeading: { flex: 1, gap: 4, minWidth: 0 },
    courseContentLessonDate: { color: '#414941', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14, textTransform: 'uppercase' },
    courseContentLessonTitle: { color: '#0b1c30', fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 28 },
    courseContentLessonText: { color: '#414941', fontFamily: fonts.sans, fontSize: 16, lineHeight: 24 },
    courseContentTypeBadge: { borderRadius: 8, fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', lineHeight: 14, paddingHorizontal: 10, paddingVertical: 5, textTransform: 'uppercase' },
    courseContentTypeTheoretical: { backgroundColor: 'rgba(254,191,49,0.2)', color: '#6e4f00' },
    courseContentTypePractical: { backgroundColor: 'rgba(0,27,8,0.1)', color: '#003215' },
    courseContentLessonFooter: { borderTopColor: 'rgba(193,201,191,0.38)', borderTopWidth: 1, paddingTop: 12 },
    courseContentFooterMeta: { alignItems: 'center', flexDirection: 'row', gap: 6 },
    courseContentFooterText: { color: '#414941', fontFamily: fonts.medium, fontSize: 13, fontWeight: '700', lineHeight: 18 },
    courseContentTaughtTimeline: { borderLeftColor: '#c1c9bf', borderLeftWidth: 2, gap: 18, marginLeft: 13, paddingLeft: 18 },
    courseContentTaughtItem: { position: 'relative' },
    courseContentCheckMarker: { alignItems: 'center', backgroundColor: '#79bb87', borderColor: '#ffffff', borderRadius: radii.pill, borderWidth: 4, height: 28, justifyContent: 'center', left: -33, position: 'absolute', top: 4, width: 28, zIndex: 2 },
    coursesAnalyticsCard: { backgroundColor: '#003215', borderRadius: 8, marginBottom: 24, marginTop: 0, minHeight: 188, overflow: 'hidden', padding: 24, position: 'relative' },
    coursesAnalyticsContent: { alignItems: 'flex-start', gap: 12, maxWidth: 280, zIndex: 1 },
    coursesAnalyticsKicker: { color: '#aef2bb', fontFamily: fonts.medium, fontSize: 11, fontWeight: '800', letterSpacing: 0, lineHeight: 14, textTransform: 'uppercase' },
    coursesAnalyticsTitle: { color: '#ffffff', fontFamily: fonts.medium, fontSize: 24, fontWeight: '800', lineHeight: 32 },
    coursesAnalyticsText: { color: '#aef2bb', fontFamily: fonts.sans, fontSize: 16, lineHeight: 24 },
    coursesAnalyticsButton: { backgroundColor: '#ffffff', borderRadius: radii.pill, marginTop: 8, paddingHorizontal: 24, paddingVertical: 8 },
    coursesAnalyticsButtonText: { color: '#003215', fontFamily: fonts.medium, fontSize: 14, fontWeight: '700' },
    coursesAnalyticsIcon: { opacity: 0.4, position: 'absolute', right: 0, top: 30 },
    secondaryButton: { alignItems: 'center', borderColor: colors.borderStrong, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', minHeight: 48, paddingHorizontal: spacing[4] },
    secondaryButtonText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 15, fontWeight: '700' },
    selectedSubjectCard: { backgroundColor: colors.brandSubtle, borderRadius: radii.md, gap: spacing[2], padding: spacing[4] },
    lessonCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[3], padding: spacing[4] },
    lessonDateBox: { alignItems: 'flex-start', backgroundColor: colors.infoSubtle, borderRadius: radii.md, gap: spacing[1], padding: spacing[3] },
    lessonDate: { color: colors.info, fontFamily: fonts.medium, fontSize: 14, fontWeight: '700' },
    lessonWorkload: { color: colors.info, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    lessonBody: { gap: 4 },
    emptyInline: { backgroundColor: colors.surfaceMuted, borderRadius: radii.md, paddingHorizontal: spacing[3], paddingVertical: spacing[4] },
    emptyInlineText: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 14, textAlign: 'center' },
    bottomNav: { ...shadows.surface, backgroundColor: colors.surfaceMuted, borderRadius: 0, flexDirection: 'row', height: 80, justifyContent: 'space-around', paddingBottom: spacing[2], paddingHorizontal: spacing[2], paddingTop: spacing[2], width: '100%' },
    bottomNavDesktop: { alignSelf: 'center', borderColor: '#c0c9be', borderRadius: radii.md, borderWidth: 1, height: 72, maxWidth: 640, width: '100%' },
    bottomNavShell: { bottom: 0, left: 0, position: 'absolute', right: 0, zIndex: 10 },
    navItem: { alignItems: 'center', borderRadius: radii.md, flex: 1, gap: spacing[1], justifyContent: 'center', minHeight: 48, paddingHorizontal: spacing[2], paddingVertical: spacing[1] },
    navItemDesktop: { flexDirection: 'row', gap: spacing[2], minHeight: 52 },
    navItemActive: { backgroundColor: colors.brandDark },
    navItemPressed: { opacity: 0.6 },
    navIconWrap: { position: 'relative' },
    navAiSparkle: { left: -7, position: 'absolute', top: -4 },
    navAiBadgeWrap: { alignItems: 'center', height: 10, justifyContent: 'center', position: 'absolute', right: -6, top: -3, width: 10 },
    navAiBadgeRing: { backgroundColor: colors.danger, borderRadius: radii.pill, height: 8, position: 'absolute', width: 8 },
    navAiBadgeDot: { backgroundColor: colors.danger, borderRadius: radii.pill, borderColor: '#ffffff', borderWidth: 1.5, height: 8, width: 8 },
    pressedFeedback: { opacity: 0.6 },
    navText: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    navTextActive: { color: colors.brandMuted },
    skeletonBlock: { backgroundColor: colors.border, borderRadius: radii.md, maxWidth: '100%', overflow: 'hidden', width: '100%' }
});
