import { Platform, StyleSheet } from 'react-native';
import { colors, fonts, radii, shadows, spacing, typography } from '@/presentation/design-system';

export const styles = StyleSheet.create({
    screen: { flex: 1 },
    appShell: { flex: 1 },
    appShellDesktop: { paddingHorizontal: 24 },
    bootScreen: { alignItems: 'center', backgroundColor: colors.canvas, flex: 1, justifyContent: 'center', padding: spacing[6] },
    bootCard: { alignItems: 'center', borderRadius: radii.md, gap: spacing[3], paddingHorizontal: spacing[7], paddingVertical: spacing[8], width: '100%' },
    bootTitle: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 24, fontWeight: '700' },
    bootText: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 15, textAlign: 'center' },
    loginScreen: { flex: 1 },
    loginContainer: { flex: 1 },
    loginScrollContent: { alignItems: 'center', flexGrow: 1, justifyContent: 'center', width: '100%' },
    loginScrollContentMobile: { justifyContent: 'flex-start' },
    loginCard: { ...shadows.surface, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, overflow: 'hidden', width: '100%' },
    loginCardWide: { flexDirection: 'row' },
    loginShowcase: { gap: spacing[6], padding: spacing[7] },
    loginShowcaseWide: { justifyContent: 'space-between', maxWidth: 420, minHeight: 520, width: '46%' },
    loginMark: { alignItems: 'center', backgroundColor: colors.overlayOnBrand, borderRadius: radii.md, height: 64, justifyContent: 'center', width: 64 },
    loginHeaderText: { gap: spacing[2] },
    eyebrow: { ...typography.eyebrow, color: colors.brandMuted, textTransform: 'uppercase' },
    loginTitle: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 30, fontWeight: '700' },
    loginSubtitle: { color: colors.brandMuted, fontFamily: fonts.sans, fontSize: 15, lineHeight: 22 },
    loginForm: { gap: spacing[5], padding: spacing[6] },
    loginFormWide: { flex: 1, justifyContent: 'center', paddingHorizontal: spacing[8], paddingVertical: spacing[7] },
    loginFormHeader: { gap: spacing[2] },
    loginFormTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 28, fontWeight: '700' },
    loginFormText: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 14, lineHeight: 20 },
    loginTrustCard: { backgroundColor: colors.overlayOnBrand, borderColor: colors.overlayBorderOnBrand, borderRadius: radii.md, borderWidth: 1, gap: spacing[3], padding: spacing[4] },
    loginFeatureLabel: { ...typography.label, color: colors.brandMuted, textTransform: 'uppercase' },
    loginFeatureValue: { color: colors.inverseText, fontFamily: fonts.sans, fontSize: 14, lineHeight: 20 },
    field: { gap: spacing[2] },
    fieldCompact: { flex: 1, minWidth: 0 },
    fieldLabel: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    textInput: { backgroundColor: colors.surfaceSubtle, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontFamily: fonts.sans, fontSize: 16, minHeight: 52, paddingHorizontal: spacing[4], paddingVertical: spacing[3] },
    passwordWrapper: { position: 'relative' },
    passwordInput: { paddingRight: 54 },
    passwordToggle: { alignItems: 'center', height: 52, justifyContent: 'center', position: 'absolute', right: 0, top: 0, width: 52 },
    primaryButton: { alignItems: 'center', backgroundColor: colors.brand, borderRadius: radii.md, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', minHeight: 54, paddingHorizontal: spacing[5] },
    primaryButtonText: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700' },
    headerShell: { alignSelf: 'center', gap: spacing[2], paddingHorizontal: spacing[5], paddingTop: spacing[3], width: '100%' },
    header: { ...shadows.surface, alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between', minHeight: 68, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    headerIdentity: { alignItems: 'center', flexDirection: 'row', flex: 1, gap: spacing[3], minWidth: 0 },
    avatarBadge: { alignItems: 'center', backgroundColor: colors.brand, borderRadius: radii.md, height: 44, justifyContent: 'center', width: 44 },
    avatarBadgeText: { color: colors.inverseText, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700' },
    headerTextStack: { flex: 1, gap: 2 },
    headerTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 20, fontWeight: '800', lineHeight: 24 },
    headerSubtitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 13, fontWeight: '600', lineHeight: 18 },
    headerActions: { alignItems: 'center', flexDirection: 'row', gap: spacing[2] },
    iconButton: { alignItems: 'center', backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, height: 42, justifyContent: 'center', width: 42 },
    desktopNav: { alignSelf: 'stretch', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', flexWrap: 'nowrap', gap: spacing[2], padding: spacing[2] },
    desktopFloatingNav: { ...shadows.surface, alignSelf: 'center', width: '100%' },
    desktopBottomNavShell: { alignItems: 'center', position: 'absolute', zIndex: 10 },
    desktopNavItem: { alignItems: 'center', borderRadius: radii.sm, flex: 1, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', minHeight: 46, paddingHorizontal: spacing[3] },
    desktopNavItemActive: { backgroundColor: colors.brandDark },
    desktopNavText: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 14, fontWeight: '700' },
    desktopNavTextActive: { color: colors.inverseText },
    content: { gap: spacing[4], paddingHorizontal: spacing[5], paddingTop: spacing[3] },
    contentShell: { alignSelf: 'center', gap: spacing[4], width: '100%' },
    errorBanner: { backgroundColor: colors.dangerSubtle, borderColor: colors.dangerBorder, borderRadius: radii.md, borderWidth: 1, paddingHorizontal: spacing[3], paddingVertical: spacing[3] },
    errorText: { color: colors.danger, fontFamily: fonts.medium, fontSize: 14, fontWeight: '600' },
    sectionStack: { gap: spacing[4] },
    panel: { ...shadows.surface, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: spacing[4], padding: spacing[5] },
    panelHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    panelTitle: { ...typography.title, color: colors.text, flexShrink: 1 },
    panelDescription: { ...typography.body, color: colors.textMuted },
    sectionKicker: { ...typography.eyebrow, color: colors.brand, textTransform: 'uppercase' },
    homeHeroRow: { gap: spacing[4] },
    homeHeroRowWide: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
    homeHeroText: { flex: 1, gap: spacing[2] },
    homeScoreCard: { alignItems: 'flex-start', backgroundColor: colors.brandSubtle, borderRadius: radii.md, gap: spacing[1], paddingHorizontal: spacing[4], paddingVertical: spacing[3], width: 140 },
    homeScoreLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    homeScoreValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 34, fontWeight: '700' },
    metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] },
    metricGridWide: { justifyContent: 'space-between' },
    metricCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexBasis: '47%', flexGrow: 1, gap: spacing[2], minHeight: 90, padding: spacing[4] },
    tileLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    tileValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: '600' },
    metricValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 30, fontWeight: '700' },
    twoColumnGrid: { gap: spacing[4] },
    twoColumnGridWide: { flexDirection: 'row', flexWrap: 'wrap' },
    gridPanel: { flex: 1, minWidth: 0 },
    highlightCard: { backgroundColor: colors.brandSubtle, borderRadius: radii.md, gap: spacing[2], padding: spacing[4] },
    highlightLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    highlightTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    highlightText: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 14 },
    highlightTime: { color: colors.brand, fontFamily: fonts.medium, fontSize: 30, fontWeight: '700', marginTop: spacing[2] },
    summaryRows: { gap: spacing[2] },
    summaryRow: { alignItems: 'center', backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between', minHeight: 48, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    summaryLabel: { color: colors.textMuted, flex: 1, fontFamily: fonts.medium, fontSize: 14, fontWeight: '600' },
    summaryValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    weekChart: { alignItems: 'flex-end', flexDirection: 'row', gap: spacing[2], justifyContent: 'space-between', minHeight: 140 },
    weekBarItem: { alignItems: 'center', flex: 1, gap: spacing[2] },
    weekBarTrack: { alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radii.md, flex: 1, justifyContent: 'flex-end', minHeight: 100, overflow: 'hidden', padding: spacing[1], width: '100%' },
    weekBarFill: { backgroundColor: colors.brand, borderRadius: radii.sm, width: '100%' },
    weekBarLabel: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    weekBarValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    gradeSummaryBoard: { gap: spacing[5] },
    gradeRing: { alignItems: 'center', alignSelf: 'center', backgroundColor: colors.brandSubtle, borderColor: colors.brandMuted, borderRadius: radii.pill, borderWidth: 12, height: 150, justifyContent: 'center', width: 150 },
    gradeRingValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 34, fontWeight: '700' },
    gradeRingLabel: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    gradeStatStack: { gap: spacing[2] },
    statPill: { backgroundColor: colors.surfaceMuted, borderRadius: radii.md, gap: spacing[1], paddingHorizontal: spacing[3], paddingVertical: spacing[3] },
    statPillValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 20, fontWeight: '700' },
    listStack: { gap: spacing[3] },
    attentionCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[1], padding: spacing[3] },
    attentionTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700' },
    attentionText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 13, fontWeight: '600' },
    profileHero: { alignItems: 'center', flexDirection: 'row', gap: spacing[4], padding: spacing[5] },
    profileAvatar: { alignItems: 'center', backgroundColor: colors.brandMuted, borderRadius: radii.md, height: 68, justifyContent: 'center', width: 68 },
    profileAvatarText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 24, fontWeight: '700' },
    profileHeroText: { flex: 1, gap: spacing[2], minWidth: 0 },
    infoTile: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexBasis: '47%', flexGrow: 1, gap: spacing[2], minHeight: 90, padding: spacing[4] },
    detailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] },
    detailCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, flexBasis: '47%', flexGrow: 1, gap: spacing[2], minHeight: 90, padding: spacing[4] },
    detailValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: '600' },
    scheduleHero: { gap: spacing[4] },
    scheduleHeroText: { gap: spacing[2] },
    timeBadge: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.infoSubtle, borderRadius: radii.md, flexDirection: 'row', gap: spacing[2], paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    timeBadgeText: { color: colors.info, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    chipsRow: { marginBottom: spacing[2] },
    weekChip: { alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radii.pill, flexDirection: 'row', gap: spacing[2], marginRight: spacing[2], paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    weekChipActive: { backgroundColor: colors.brandMuted },
    weekChipText: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    weekChipTextActive: { color: colors.brand },
    weekChipNumber: { color: colors.text, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    laneCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[3], padding: spacing[4] },
    laneHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    scheduleEvent: { borderRadius: radii.md, flexDirection: 'row', gap: spacing[3], padding: spacing[3] },
    eventToneGreen: { backgroundColor: colors.successSubtle },
    eventToneBlue: { backgroundColor: colors.infoSubtle },
    eventToneAmber: { backgroundColor: colors.warningSubtle },
    eventToneCoral: { backgroundColor: colors.dangerSubtle },
    eventTimeBox: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radii.md, justifyContent: 'center', minHeight: 64, paddingHorizontal: spacing[3], width: 88 },
    eventTimePrimary: { color: colors.text, fontFamily: fonts.medium, fontSize: 18, fontWeight: '700' },
    eventTimeSecondary: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 12 },
    eventBody: { flex: 1, gap: spacing[1], minWidth: 0 },
    smallCaps: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    eventTitle: { color: colors.text, fontFamily: fonts.medium, fontSize: 16, fontWeight: '700', lineHeight: 21 },
    eventSubtitle: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 13 },
    bigNumber: { color: colors.text, fontFamily: fonts.medium, fontSize: 48, fontWeight: '700' },
    gradeOverviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
    inputRow: { alignItems: 'flex-end', flexDirection: 'row', gap: spacing[2] },
    inputRowWide: { alignItems: 'stretch' },
    gradeCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[4], padding: spacing[4] },
    gradeHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing[3], justifyContent: 'space-between' },
    gradeHeaderText: { flex: 1, gap: spacing[1], minWidth: 0 },
    statusPill: { borderRadius: radii.pill, flexShrink: 1, paddingHorizontal: spacing[3], paddingVertical: spacing[2] },
    statusOk: { backgroundColor: colors.successSubtle },
    statusWarn: { backgroundColor: colors.warningSubtle },
    statusDanger: { backgroundColor: colors.dangerSubtle },
    statusPillText: { color: colors.text, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    horizontalList: { marginHorizontal: -2 },
    evaluationCard: { backgroundColor: colors.surface, borderRadius: radii.md, gap: spacing[2], marginRight: spacing[2], padding: spacing[4], width: 138 },
    evaluationBadge: { alignItems: 'center', backgroundColor: colors.brandMuted, borderRadius: radii.sm, height: 28, justifyContent: 'center', width: 28 },
    evaluationBadgeText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 13, fontWeight: '700' },
    evaluationScore: { color: colors.text, fontFamily: fonts.medium, fontSize: 26, fontWeight: '700' },
    miniGradeCard: { backgroundColor: colors.surface, borderRadius: radii.md, flexBasis: '47%', flexGrow: 1, gap: spacing[2], padding: spacing[4] },
    miniGradeCardFeatured: { backgroundColor: colors.brandMuted },
    miniGradeValue: { color: colors.text, fontFamily: fonts.medium, fontSize: 24, fontWeight: '700' },
    miniGradeValueFeatured: { color: colors.brand },
    subjectChip: { backgroundColor: colors.surfaceMuted, borderRadius: radii.md, gap: spacing[1], marginRight: spacing[2], paddingHorizontal: spacing[3], paddingVertical: spacing[3], width: 176 },
    subjectChipActive: { backgroundColor: colors.brandDark },
    subjectChipCode: { ...typography.label, color: colors.textMuted, textTransform: 'uppercase' },
    subjectChipCodeActive: { color: colors.brandMuted },
    subjectChipText: { color: colors.text, fontFamily: fonts.medium, fontSize: 14, fontWeight: '600' },
    subjectChipTextActive: { color: colors.inverseText },
    secondaryButton: { alignItems: 'center', borderColor: colors.borderStrong, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', minHeight: 48, paddingHorizontal: spacing[4] },
    secondaryButtonText: { color: colors.brand, fontFamily: fonts.medium, fontSize: 15, fontWeight: '700' },
    selectedSubjectCard: { backgroundColor: colors.brandSubtle, borderRadius: radii.md, gap: spacing[2], padding: spacing[4] },
    lessonCard: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, gap: spacing[3], padding: spacing[4] },
    lessonDateBox: { alignItems: 'flex-start', backgroundColor: colors.infoSubtle, borderRadius: radii.md, gap: spacing[1], padding: spacing[3] },
    lessonDate: { color: colors.info, fontFamily: fonts.medium, fontSize: 14, fontWeight: '700' },
    lessonWorkload: { color: colors.info, fontFamily: fonts.medium, fontSize: 12, fontWeight: '700' },
    lessonBody: { gap: 4 },
    emptyInline: { backgroundColor: colors.surfaceMuted, borderRadius: radii.md, paddingHorizontal: spacing[3], paddingVertical: spacing[4] },
    emptyInlineText: { color: colors.textMuted, fontFamily: fonts.sans, fontSize: 14, textAlign: 'center' },
    bottomNav: { ...shadows.surface, alignSelf: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', maxWidth: 560, paddingBottom: Platform.OS === 'ios' ? 18 : 14, paddingHorizontal: spacing[2], paddingTop: spacing[2], width: '100%' },
    bottomNavShell: { position: 'absolute', zIndex: 10 },
    navItem: { alignItems: 'center', borderRadius: radii.sm, flex: 1, gap: spacing[1], paddingVertical: spacing[2] },
    navItemActive: { backgroundColor: colors.brandMuted },
    navText: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 11, fontWeight: '700' },
    navTextActive: { color: colors.brand },
    skeletonBlock: { backgroundColor: colors.border, borderRadius: radii.md }
});
